date.timezone = Europe/Moscow
expose_php = Off
upload_max_filesize = 64M
post_max_size = 65M
max_execution_time = 700
memory_limit = 512M
allow_url_fopen = On
magic_quotes_gpc = Off
short_open_tag = On
always_populate_raw_post_data = -1
apc.enable_cli=1